// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: emails.sql

package core

import (
	"context"
)

const addEmail = `-- name: AddEmail :exec
INSERT INTO emails (
  email
) VALUES (
  $1
)
`

func (q *Queries) AddEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, addEmail, email)
	return err
}

const getAll = `-- name: GetAll :many
SELECT email FROM emails
`

func (q *Queries) GetAll(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
